name: Bash script example

on: [push]

jobs:
  build:
    runs-on: kali-linux/latest
    working-directory: _work
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          #!/bin/bash
          echo "puuuuush"
