name: Deploy Express App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Stop previous app
        run: sudo systemctl stop expressTest.service
      - name: Copy files
        run: sudo cp -r . /home/kali/deploy
      - name: Start app
        run: sudo systemctl start expressTest.service
